[package]
name = "rust-cli-timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
notify-rust = "4"
indicatif = "0.17.8"
